//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidApplication1
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int black = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int lightgray = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int listseparator = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int attachment = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Comments = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Description = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int details_list = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Green = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Labels = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Likes = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Logo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Members = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Orange = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Purple = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Red = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Yellow = 2130837518;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002a
			public const int MyButton = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int Text1 = 2131099692;
			
			// aapt resource value: 0x7f060028
			public const int imageView1 = 2131099688;
			
			// aapt resource value: 0x7f06000c
			public const int imgBadge1 = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int imgBadge2 = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int imgBadge3 = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int imgBadge4 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int imgBadge5 = 2131099668;
			
			// aapt resource value: 0x7f06001b
			public const int imgLabel1 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int imgLabel2 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int imgLabel3 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int imgLabel4 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int imgLabel5 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int imgLabel6 = 2131099680;
			
			// aapt resource value: 0x7f060002
			public const int imgLagel1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int imgLagel2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int imgLagel3 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int imgLagel4 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int imgLagel5 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int imgLagel6 = 2131099655;
			
			// aapt resource value: 0x7f060015
			public const int imgMembership = 2131099669;
			
			// aapt resource value: 0x7f060026
			public const int imgMemebers = 2131099686;
			
			// aapt resource value: 0x7f06000a
			public const int layInfo = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int layLabels = 2131099649;
			
			// aapt resource value: 0x7f060027
			public const int layMembers = 2131099687;
			
			// aapt resource value: 0x7f060000
			public const int mainCardLayout = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int textCard = 2131099657;
			
			// aapt resource value: 0x7f060022
			public const int txtAttach = 2131099682;
			
			// aapt resource value: 0x7f06000b
			public const int txtBadge1 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int txtBadge2 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int txtBadge3 = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int txtBadge4 = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int txtBadge5 = 2131099667;
			
			// aapt resource value: 0x7f060024
			public const int txtCheck = 2131099684;
			
			// aapt resource value: 0x7f060023
			public const int txtComment = 2131099683;
			
			// aapt resource value: 0x7f060019
			public const int txtDesc = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int txtName = 2131099671;
			
			// aapt resource value: 0x7f060025
			public const int txtVotes = 2131099685;
			
			// aapt resource value: 0x7f060029
			public const int txtWelcome = 2131099689;
			
			// aapt resource value: 0x7f06002b
			public const int webView1 = 2131099691;
			
			// aapt resource value: 0x7f060016
			public const int widget33 = 2131099670;
			
			// aapt resource value: 0x7f060008
			public const int widget34 = 2131099656;
			
			// aapt resource value: 0x7f060018
			public const int widget45 = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int widget46 = 2131099674;
			
			// aapt resource value: 0x7f060021
			public const int widget60 = 2131099681;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Boards = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Cards = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Details = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int OrganizationHeaderSection = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			private String()
			{
			}
		}
	}
}
